# TODO: research wildcard targets

en: figures
	cp ../en/*/*.markdown ./_docs/

de: figures
	cp ../de/*/*.markdown ./_docs/

figures:
	mkdir -p _attachments/figures/
	cp ../figures/* _attachments/figures/

clean:
	git clean -fdx
